"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const express = require("express");
const render_middleware_1 = require("../middlewares/render-middleware");
const authenticated_middleware_1 = require("../middlewares/authenticated-middleware");
const get_modified_event_middleware_1 = require("../middlewares/event/get-modified-event-middleware");
const participate_middleware_1 = require("../middlewares/event/participate-middleware");
const redirect_middleware_1 = require("../middlewares/redirect-middleware");
const create_update_event_middleware_1 = require("../middlewares/event/create-update-event-middleware");
const delete_event_middleware_1 = require("../middlewares/event/delete-event-middleware");
const router = express.Router();
router.use(authenticated_middleware_1.default());
router.get("/", render_middleware_1.default("create.html"));
router.post("/", create_update_event_middleware_1.default(), redirect_middleware_1.default("/"));
router.get("/:eventId", get_modified_event_middleware_1.default(), render_middleware_1.default("create.html"));
router.post("/:eventId", get_modified_event_middleware_1.default(), create_update_event_middleware_1.default(), redirect_middleware_1.default("/"));
router.post("/:eventId/status", participate_middleware_1.default(), redirect_middleware_1.default("/"));
router.delete("/:eventId", get_modified_event_middleware_1.default(), delete_event_middleware_1.default(), redirect_middleware_1.default("/"));
exports.default = router;
//# sourceMappingURL=event-router.js.map